<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('name', 64);
            $table->string('iso', 2);
            $table->char('have_state', 1)->default(0);
            $table->char('have_province', 1)->default(1);
            $table->char('status', 1)->default(1);
        });

        DB::table('countries')->insert([
            ["name" => "United States","iso"=> "US","have_state"=>"1","have_province"=>"0"],
            ["name" => "Afghanistan","iso"=> "AF","have_state"=>"0","have_province"=>"1"],
            ["name" => "Albania","iso"=> "AL","have_state"=>"0","have_province"=>"0"],
            ["name" => "Algeria","iso"=> "DZ","have_state"=>"0","have_province"=>"1"],
            ["name" => "American Samoa","iso"=> "AS","have_state"=>"0","have_province"=>"0"],
            ["name" => "Andorra","iso"=> "AD","have_state"=>"0","have_province"=>"0"],
            ["name" => "Angola","iso"=> "AO","have_state"=>"0","have_province"=>"1"],
            ["name" => "Anguilla","iso"=> "AI","have_state"=>"0","have_province"=>"0"],
            ["name" => "Antarctica","iso"=> "AQ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Antigua and Barbuda","iso"=> "AG","have_state"=>"0","have_province"=>"0"],
            ["name" => "Argentina","iso"=> "AR","have_state"=>"0","have_province"=>"1"],
            ["name" => "Armenia","iso"=> "AM","have_state"=>"0","have_province"=>"1"],
            ["name" => "Aruba","iso"=> "AW","have_state"=>"0","have_province"=>"0"],
            ["name" => "Australia","iso"=> "AU","have_state"=>"1","have_province"=>"0"],
            ["name" => "Austria","iso"=> "AT","have_state"=>"0","have_province"=>"0"],
            ["name" => "Azerbaijan","iso"=> "AZ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Bahamas","iso"=> "BS","have_state"=>"0","have_province"=>"0"],
            ["name" => "Bahrain","iso"=> "BH","have_state"=>"0","have_province"=>"0"],
            ["name" => "Bangladesh","iso"=> "BD","have_state"=>"0","have_province"=>"0"],
            ["name" => "Barbados","iso"=> "BB","have_state"=>"0","have_province"=>"0"],
            ["name" => "Belarus","iso"=> "BY","have_state"=>"0","have_province"=>"1"],
            ["name" => "Belgium","iso"=> "BE","have_state"=>"0","have_province"=>"1"],
            ["name" => "Belize","iso"=> "BZ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Benin","iso"=> "BJ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Bermuda","iso"=> "BM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Bhutan","iso"=> "BT","have_state"=>"0","have_province"=>"0"],
            ["name" => "Bolivia","iso"=> "BO","have_state"=>"0","have_province"=>"1"],
            ["name" => "Bonaire","iso"=> "BQ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Bosnia and Herzegovina","iso"=> "BA","have_state"=>"0","have_province"=>"0"],
            ["name" => "Botswana","iso"=> "BW","have_state"=>"0","have_province"=>"0"],
            ["name" => "Bouvet Island","iso"=> "BV","have_state"=>"0","have_province"=>"0"],
            ["name" => "Brazil","iso"=> "BR","have_state"=>"1","have_province"=>"0"],
            ["name" => "British Indian Ocean Territory","iso"=> "IO","have_state"=>"0","have_province"=>"0"],
            ["name" => "Brunei Darussalam","iso"=> "BN","have_state"=>"0","have_province"=>"0"],
            ["name" => "Bulgaria","iso"=> "BG","have_state"=>"0","have_province"=>"1"],
            ["name" => "Burkina Faso","iso"=> "BF","have_state"=>"0","have_province"=>"1"],
            ["name" => "Burundi","iso"=> "BI","have_state"=>"0","have_province"=>"1"],
            ["name" => "Cambodia","iso"=> "KH","have_state"=>"0","have_province"=>"1"],
            ["name" => "Cameroon","iso"=> "CM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Canada","iso"=> "CA","have_state"=>"0","have_province"=>"1"],
            ["name" => "Cape Verde","iso"=> "CV","have_state"=>"0","have_province"=>"0"],
            ["name" => "Cayman Islands","iso"=> "KY","have_state"=>"0","have_province"=>"0"],
            ["name" => "Central African Republic","iso"=> "CF","have_state"=>"0","have_province"=>"0"],
            ["name" => "Chad","iso"=> "TD","have_state"=>"0","have_province"=>"0"],
            ["name" => "Chile","iso"=> "CL","have_state"=>"0","have_province"=>"1"],
            ["name" => "China","iso"=> "CN","have_state"=>"0","have_province"=>"1"],
            ["name" => "Christmas Island","iso"=> "CX","have_state"=>"0","have_province"=>"0"],
            ["name" => "Cocos (Keeling) Islands","iso"=> "CC","have_state"=>"0","have_province"=>"0"],
            ["name" => "Colombia","iso"=> "CO","have_state"=>"0","have_province"=>"0"],
            ["name" => "Comoros","iso"=> "KM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Congo","iso"=> "CG","have_state"=>"0","have_province"=>"0"],
            ["name" => "Democratic Republic of the Congo","iso"=> "CD","have_state"=>"0","have_province"=>"1"],
            ["name" => "Cook Islands","iso"=> "CK","have_state"=>"0","have_province"=>"0"],
            ["name" => "Costa Rica","iso"=> "CR","have_state"=>"0","have_province"=>"1"],
            ["name" => "CÃ´te d'Ivoire","iso"=> "CI","have_state"=>"0","have_province"=>"0"],
            ["name" => "Croatia","iso"=> "HR","have_state"=>"0","have_province"=>"0"],
            ["name" => "Cuba","iso"=> "CU","have_state"=>"0","have_province"=>"1"],
            ["name" => "CuraÃ§ao","iso"=> "CW","have_state"=>"0","have_province"=>"0"],
            ["name" => "Cyprus","iso"=> "CY","have_state"=>"0","have_province"=>"0"],
            ["name" => "Czech Republic","iso"=> "CZ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Denmark","iso"=> "DK","have_state"=>"0","have_province"=>"0"],
            ["name" => "Djibouti","iso"=> "DJ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Dominica","iso"=> "DM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Dominican Republic","iso"=> "DO","have_state"=>"0","have_province"=>"1"],
            ["name" => "Ecuador","iso"=> "EC","have_state"=>"0","have_province"=>"1"],
            ["name" => "Egypt","iso"=> "EG","have_state"=>"0","have_province"=>"0"],
            ["name" => "El Salvador","iso"=> "SV","have_state"=>"0","have_province"=>"0"],
            ["name" => "Equatorial Guinea","iso"=> "GQ","have_state"=>"0","have_province"=>"1"],
            ["name" => "Eritrea","iso"=> "ER","have_state"=>"0","have_province"=>"0"],
            ["name" => "Estonia","iso"=> "EE","have_state"=>"0","have_province"=>"0"],
            ["name" => "Ethiopia","iso"=> "ET","have_state"=>"1","have_province"=>"0"],
            ["name" => "Falkland Islands (Malvinas)","iso"=> "FK","have_state"=>"0","have_province"=>"0"],
            ["name" => "Faroe Islands","iso"=> "FO","have_state"=>"0","have_province"=>"0"],
            ["name" => "Fiji","iso"=> "FJ","have_state"=>"0","have_province"=>"1"],
            ["name" => "Finland","iso"=> "FI","have_state"=>"0","have_province"=>"1"],
            ["name" => "France","iso"=> "FR","have_state"=>"0","have_province"=>"0"],
            ["name" => "French Guiana","iso"=> "GF","have_state"=>"0","have_province"=>"0"],
            ["name" => "French Polynesia","iso"=> "PF","have_state"=>"0","have_province"=>"0"],
            ["name" => "French Southern Territories","iso"=> "TF","have_state"=>"0","have_province"=>"0"],
            ["name" => "Gabon","iso"=> "GA","have_state"=>"0","have_province"=>"1"],
            ["name" => "Gambia","iso"=> "GM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Georgia","iso"=> "GE","have_state"=>"0","have_province"=>"1"],
            ["name" => "Germany","iso"=> "DE","have_state"=>"1","have_province"=>"0"],
            ["name" => "Ghana","iso"=> "GH","have_state"=>"0","have_province"=>"0"],
            ["name" => "Gibraltar","iso"=> "GI","have_state"=>"0","have_province"=>"0"],
            ["name" => "Greece","iso"=> "GR","have_state"=>"0","have_province"=>"1"],
            ["name" => "Greenland","iso"=> "GL","have_state"=>"0","have_province"=>"0"],
            ["name" => "Grenada","iso"=> "GD","have_state"=>"0","have_province"=>"0"],
            ["name" => "Guadeloupe","iso"=> "GP","have_state"=>"0","have_province"=>"0"],
            ["name" => "Guam","iso"=> "GU","have_state"=>"0","have_province"=>"0"],
            ["name" => "Guatemala","iso"=> "GT","have_state"=>"0","have_province"=>"0"],
            ["name" => "Guernsey","iso"=> "GG","have_state"=>"0","have_province"=>"0"],
            ["name" => "Guinea","iso"=> "GN","have_state"=>"0","have_province"=>"0"],
            ["name" => "Guinea-Bissau","iso"=> "GW","have_state"=>"0","have_province"=>"0"],
            ["name" => "Guyana","iso"=> "GY","have_state"=>"0","have_province"=>"0"],
            ["name" => "Haiti","iso"=> "HT","have_state"=>"0","have_province"=>"0"],
            ["name" => "Heard Island and McDonald Islands","iso"=> "HM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Holy See (Vatican City State)","iso"=> "VA","have_state"=>"0","have_province"=>"0"],
            ["name" => "Honduras","iso"=> "HN","have_state"=>"0","have_province"=>"0"],
            ["name" => "Hong Kong","iso"=> "HK","have_state"=>"0","have_province"=>"0"],
            ["name" => "Hungary","iso"=> "HU","have_state"=>"0","have_province"=>"0"],
            ["name" => "Iceland","iso"=> "IS","have_state"=>"0","have_province"=>"0"],
            ["name" => "India","iso"=> "IN","have_state"=>"1","have_province"=>"0"],
            ["name" => "Indonesia","iso"=> "ID","have_state"=>"0","have_province"=>"1"],
            ["name" => "Iran","iso"=> "IR","have_state"=>"0","have_province"=>"1"],
            ["name" => "Iraq","iso"=> "IQ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Ireland","iso"=> "IE","have_state"=>"0","have_province"=>"1"],
            ["name" => "Isle of Man","iso"=> "IM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Israel","iso"=> "IL","have_state"=>"0","have_province"=>"0"],
            ["name" => "Italy","iso"=> "IT","have_state"=>"0","have_province"=>"1"],
            ["name" => "Jamaica","iso"=> "JM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Japan","iso"=> "JP","have_state"=>"0","have_province"=>"0"],
            ["name" => "Jersey","iso"=> "JE","have_state"=>"0","have_province"=>"0"],
            ["name" => "Jordan","iso"=> "JO","have_state"=>"0","have_province"=>"0"],
            ["name" => "Kazakhstan","iso"=> "KZ","have_state"=>"0","have_province"=>"1"],
            ["name" => "Kenya","iso"=> "KE","have_state"=>"0","have_province"=>"1"],
            ["name" => "Kiribati","iso"=> "KI","have_state"=>"0","have_province"=>"0"],
            ["name" => "Korea, Democratic People's Republic of","iso"=> "KP","have_state"=>"0","have_province"=>"1"],
            ["name" => "Korea,Republic of","iso"=> "KR","have_state"=>"0","have_province"=>"1"],
            ["name" => "Kuwait","iso"=> "KW","have_state"=>"0","have_province"=>"0"],
            ["name" => "Kyrgyzstan","iso"=> "KG","have_state"=>"0","have_province"=>"1"],
            ["name" => "Lao People's Democratic Republic","iso"=> "LA","have_state"=>"0","have_province"=>"0"],
            ["name" => "Latvia","iso"=> "LV","have_state"=>"0","have_province"=>"0"],
            ["name" => "Lebanon","iso"=> "LB","have_state"=>"0","have_province"=>"0"],
            ["name" => "Lesotho","iso"=> "LS","have_state"=>"0","have_province"=>"0"],
            ["name" => "Liberia","iso"=> "LR","have_state"=>"0","have_province"=>"0"],
            ["name" => "Libya","iso"=> "LY","have_state"=>"0","have_province"=>"0"],
            ["name" => "Liechtenstein","iso"=> "LI","have_state"=>"0","have_province"=>"0"],
            ["name" => "Lithuania","iso"=> "LT","have_state"=>"0","have_province"=>"0"],
            ["name" => "Luxembourg","iso"=> "LU","have_state"=>"0","have_province"=>"0"],
            ["name" => "Macao","iso"=> "MO","have_state"=>"0","have_province"=>"0"],
            ["name" => "Macedonia, the Former Yugoslav Republic of","iso"=> "MK","have_state"=>"0","have_province"=>"0"],
            ["name" => "Madagascar","iso"=> "MG","have_state"=>"0","have_province"=>"1"],
            ["name" => "Malawi","iso"=> "MW","have_state"=>"0","have_province"=>"0"],
            ["name" => "Malaysia","iso"=> "MY","have_state"=>"0","have_province"=>"0"],
            ["name" => "Maldives","iso"=> "MV","have_state"=>"0","have_province"=>"0"],
            ["name" => "Mali","iso"=> "ML","have_state"=>"0","have_province"=>"0"],
            ["name" => "Malta","iso"=> "MT","have_state"=>"0","have_province"=>"0"],
            ["name" => "Marshall Islands","iso"=> "MH","have_state"=>"0","have_province"=>"0"],
            ["name" => "Martinique","iso"=> "MQ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Mauritania","iso"=> "MR","have_state"=>"0","have_province"=>"0"],
            ["name" => "Mauritius","iso"=> "MU","have_state"=>"0","have_province"=>"0"],
            ["name" => "Mayotte","iso"=> "YT","have_state"=>"0","have_province"=>"0"],
            ["name" => "Mexico","iso"=> "MX","have_state"=>"1","have_province"=>"0"],
            ["name" => "Micronesia, Federated States of","iso"=> "FM","have_state"=>"1","have_province"=>"0"],
            ["name" => "Moldova, Republic of","iso"=> "MD","have_state"=>"0","have_province"=>"0"],
            ["name" => "Monaco","iso"=> "MC","have_state"=>"0","have_province"=>"0"],
            ["name" => "Mongolia","iso"=> "MN","have_state"=>"0","have_province"=>"1"],
            ["name" => "Montenegro","iso"=> "ME","have_state"=>"0","have_province"=>"0"],
            ["name" => "Montserrat","iso"=> "MS","have_state"=>"0","have_province"=>"0"],
            ["name" => "Morocco","iso"=> "MA","have_state"=>"0","have_province"=>"0"],
            ["name" => "Mozambique","iso"=> "MZ","have_state"=>"0","have_province"=>"1"],
            ["name" => "Myanmar","iso"=> "MM","have_state"=>"1","have_province"=>"0"],
            ["name" => "Namibia","iso"=> "NA","have_state"=>"0","have_province"=>"0"],
            ["name" => "Nauru","iso"=> "NR","have_state"=>"0","have_province"=>"0"],
            ["name" => "Nepal","iso"=> "NP","have_state"=>"0","have_province"=>"1"],
            ["name" => "Netherlands","iso"=> "NL","have_state"=>"0","have_province"=>"1"],
            ["name" => "New Caledonia","iso"=> "NC","have_state"=>"0","have_province"=>"0"],
            ["name" => "New Zealand","iso"=> "NZ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Nicaragua","iso"=> "NI","have_state"=>"0","have_province"=>"0"],
            ["name" => "Niger","iso"=> "NE","have_state"=>"0","have_province"=>"0"],
            ["name" => "Nigeria","iso"=> "NG","have_state"=>"1","have_province"=>"0"],
            ["name" => "Niue","iso"=> "NU","have_state"=>"0","have_province"=>"0"],
            ["name" => "Norfolk Island","iso"=> "NF","have_state"=>"0","have_province"=>"0"],
            ["name" => "Northern Mariana Islands","iso"=> "MP","have_state"=>"0","have_province"=>"0"],
            ["name" => "Norway","iso"=> "NO","have_state"=>"0","have_province"=>"1"],
            ["name" => "Oman","iso"=> "OM","have_state"=>"0","have_province"=>"1"],
            ["name" => "Pakistan","iso"=> "PK","have_state"=>"0","have_province"=>"1"],
            ["name" => "Palau","iso"=> "PW","have_state"=>"1","have_province"=>"0"],
            ["name" => "Palestine, State of","iso"=> "PS","have_state"=>"0","have_province"=>"0"],
            ["name" => "Panama","iso"=> "PA","have_state"=>"0","have_province"=>"1"],
            ["name" => "Papua New Guinea","iso"=> "PG","have_state"=>"0","have_province"=>"1"],
            ["name" => "Paraguay","iso"=> "PY","have_state"=>"0","have_province"=>"0"],
            ["name" => "Peru","iso"=> "PE","have_state"=>"0","have_province"=>"1"],
            ["name" => "Philippines","iso"=> "PH","have_state"=>"0","have_province"=>"1"],
            ["name" => "Pitcairn","iso"=> "PN","have_state"=>"0","have_province"=>"0"],
            ["name" => "Poland","iso"=> "PL","have_state"=>"0","have_province"=>"0"],
            ["name" => "Portugal","iso"=> "PT","have_state"=>"0","have_province"=>"0"],
            ["name" => "Puerto Rico","iso"=> "PR","have_state"=>"0","have_province"=>"0"],
            ["name" => "Qatar","iso"=> "QA","have_state"=>"0","have_province"=>"0"],
            ["name" => "RÃ©union","iso"=> "RE","have_state"=>"0","have_province"=>"0"],
            ["name" => "Romania","iso"=> "RO","have_state"=>"0","have_province"=>"1"],
            ["name" => "Russian Federation","iso"=> "RU","have_state"=>"0","have_province"=>"0"],
            ["name" => "Rwanda","iso"=> "RW","have_state"=>"0","have_province"=>"1"],
            ["name" => "Saint BarthÃ©lemy","iso"=> "BL","have_state"=>"0","have_province"=>"0"],
            ["name" => "Saint Helena, Ascension and Tristan da Cunha","iso"=> "SH","have_state"=>"0","have_province"=>"0"],
            ["name" => "Saint Kitts and Nevis","iso"=> "KN","have_state"=>"0","have_province"=>"0"],
            ["name" => "Saint Lucia","iso"=> "LC","have_state"=>"0","have_province"=>"0"],
            ["name" => "Saint Martin (French part)","iso"=> "MF","have_state"=>"0","have_province"=>"0"],
            ["name" => "Saint Pierre and Miquelon","iso"=> "PM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Saint Vincent and the Grenadines","iso"=> "VC","have_state"=>"0","have_province"=>"0"],
            ["name" => "Samoa","iso"=> "WS","have_state"=>"0","have_province"=>"0"],
            ["name" => "San Marino","iso"=> "SM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Sao Tome and Principe","iso"=> "ST","have_state"=>"0","have_province"=>"0"],
            ["name" => "Saudi Arabia","iso"=> "SA","have_state"=>"0","have_province"=>"1"],
            ["name" => "Senegal","iso"=> "SN","have_state"=>"0","have_province"=>"0"],
            ["name" => "Serbia","iso"=> "RS","have_state"=>"0","have_province"=>"0"],
            ["name" => "Seychelles","iso"=> "SC","have_state"=>"0","have_province"=>"0"],
            ["name" => "Sierra Leone","iso"=> "SL","have_state"=>"0","have_province"=>"1"],
            ["name" => "Singapore","iso"=> "SG","have_state"=>"0","have_province"=>"0"],
            ["name" => "Sint Maarten (Dutch part)","iso"=> "SX","have_state"=>"0","have_province"=>"0"],
            ["name" => "Slovakia","iso"=> "SK","have_state"=>"0","have_province"=>"0"],
            ["name" => "Slovenia","iso"=> "SI","have_state"=>"0","have_province"=>"0"],
            ["name" => "Solomon Islands","iso"=> "SB","have_state"=>"0","have_province"=>"1"],
            ["name" => "Somalia","iso"=> "SO","have_state"=>"0","have_province"=>"0"],
            ["name" => "South Africa","iso"=> "ZA","have_state"=>"0","have_province"=>"1"],
            ["name" => "South Georgia and the South Sandwich Islands","iso"=> "GS","have_state"=>"0","have_province"=>"0"],
            ["name" => "South Sudan","iso"=> "SS","have_state"=>"1","have_province"=>"0"],
            ["name" => "Spain","iso"=> "ES","have_state"=>"0","have_province"=>"1"],
            ["name" => "Sri Lanka","iso"=> "LK","have_state"=>"0","have_province"=>"1"],
            ["name" => "Sudan","iso"=> "SD","have_state"=>"0","have_province"=>"0"],
            ["name" => "Suriname","iso"=> "SR","have_state"=>"0","have_province"=>"1"],
            ["name" => "Svalbard and Jan Mayen","iso"=> "SJ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Swaziland","iso"=> "SZ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Sweden","iso"=> "SE","have_state"=>"0","have_province"=>"0"],
            ["name" => "Switzerland","iso"=> "CH","have_state"=>"0","have_province"=>"0"],
            ["name" => "Syrian Arab Republic","iso"=> "SY","have_state"=>"0","have_province"=>"0"],
            ["name" => "Taiwan, Province of China","iso"=> "TW","have_state"=>"0","have_province"=>"0"],
            ["name" => "Tajikistan","iso"=> "TJ","have_state"=>"0","have_province"=>"1"],
            ["name" => "Tanzania, United Republic of","iso"=> "TZ","have_state"=>"0","have_province"=>"0"],
            ["name" => "Thailand","iso"=> "TH","have_state"=>"0","have_province"=>"0"],
            ["name" => "Timor-Leste","iso"=> "TL","have_state"=>"0","have_province"=>"1"],
            ["name" => "Togo","iso"=> "TG","have_state"=>"0","have_province"=>"0"],
            ["name" => "Tokelau","iso"=> "TK","have_state"=>"0","have_province"=>"0"],
            ["name" => "Tonga","iso"=> "TO","have_state"=>"0","have_province"=>"1"],
            ["name" => "Trinidad and Tobago","iso"=> "TT","have_state"=>"0","have_province"=>"0"],
            ["name" => "Tunisia","iso"=> "TN","have_state"=>"0","have_province"=>"0"],
            ["name" => "Turkey","iso"=> "TR","have_state"=>"0","have_province"=>"1"],
            ["name" => "Turkmenistan","iso"=> "TM","have_state"=>"0","have_province"=>"1"],
            ["name" => "Turks and Caicos Islands","iso"=> "TC","have_state"=>"0","have_province"=>"0"],
            ["name" => "Tuvalu","iso"=> "TV","have_state"=>"0","have_province"=>"0"],
            ["name" => "Uganda","iso"=> "UG","have_state"=>"0","have_province"=>"0"],
            ["name" => "Ukraine","iso"=> "UA","have_state"=>"0","have_province"=>"1"],
            ["name" => "United Arab Emirates","iso"=> "AE","have_state"=>"0","have_province"=>"0"],
            ["name" => "United Kingdom","iso"=> "GB","have_state"=>"0","have_province"=>"0"],
            ["name" => "United States Minor Outlying Islands","iso"=> "UM","have_state"=>"0","have_province"=>"0"],
            ["name" => "Uruguay","iso"=> "UY","have_state"=>"0","have_province"=>"0"],
            ["name" => "Uzbekistan","iso"=> "UZ","have_state"=>"0","have_province"=>"1"],
            ["name" => "Vanuatu","iso"=> "VU","have_state"=>"0","have_province"=>"1"],
            ["name" => "Venezuela, Bolivarian Republic of","iso"=> "VE","have_state"=>"0","have_province"=>"0"],
            ["name" => "VietNam","iso"=> "VN","have_state"=>"0","have_province"=>"1"],
            ["name" => "Virgin Islands, British","iso"=> "VG","have_state"=>"0","have_province"=>"0"],
            ["name" => "Virgin Islands, U.S.","iso"=> "VI","have_state"=>"0","have_province"=>"0"],
            ["name" => "Wallis and Futuna","iso"=> "WF","have_state"=>"0","have_province"=>"0"],
            ["name" => "Western Sahara","iso"=> "EH","have_state"=>"0","have_province"=>"0"],
            ["name" => "Yemen","iso"=> "YE","have_state"=>"0","have_province"=>"0"],
            ["name" => "Zambia","iso"=> "ZM","have_state"=>"0","have_province"=>"1"],
            ["name" => "Zimbabwe","iso"=> "ZW","have_state"=>"0","have_province"=>"1"]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
