<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateExchangeTradedsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('exchange_tradeds', function (Blueprint $table) {
            $table->id();
            $table->string('name', 128);
            $table->char('status', 1)->default(1);
        });

        DB::table('exchange_tradeds')->insert([
            ["name" => "United States of America, NASDAQ (NASDAQ), (XNAS)"],
            ["name" => "United States of America, New York Stock Exchange (NYSE), (XNYS)"],
            ["name" => "United States of America, CBOE BZX U.S. Equities Exchange (BATS), (BATS)"],
            ["name" => "United States of America, Chicago Stock Exchange (CHX), (XCHI)"],
            ["name" => "United States of America, Investors Exchange (IEX), (IEXG)"],
            ["name" => "United States of America, Long-Term Stock Exchange (LTSE), (LTSE)"],
            ["name" => "United States of America, Miami International Securities Exchange (XMIO), (XMIO)"],
            ["name" => "United States of America, OTCQX Marketplace, (OTCQ)"],
            ["name" => "United States of America, OTCQB Marketplace, (OTCB)"],
            ["name" => "United States of America, OTC Pink Marketplace, (PINX)"],
            ["name" => "United States of America, OTCBB (OTCBB), (XOTC)"],
            ["name" => "United States of America, OTC Grey Market, (PSGM)"],
            ["name" => "Albania, Tirana Stock Exchange, (XTIR)"],
            ["name" => "Albania, Albanian Securities Exchange (ALSE), (XALS)"],
            ["name" => "Angola, BODIVA (BODIVA), (XBDV)"],
            ["name" => "Argentina, Buenos Aires Stock Exchange (BCBA), (XBUE)"],
            ["name" => "Argentina, Mercado Abierto Electrónico (MAE), (XMAB)"],
            ["name" => "Armenia, Armenia Securities Exchange (ARMEX), (XARM)"],
            ["name" => "Australia, Chi-X Australia, (CHIA)"],
            ["name" => "Australia, Australian Securities Exchange (ASX), (XASX)"],
            ["name" => "Australia, Block Event, (BLEV)"],
            ["name" => "Australia, IR Plus Securities Exchange, (SIMV)"],
            ["name" => "Australia, National Stock Exchange of Australia (NSXA), (XNEC)"],
            ["name" => "Australia, Sydney Stock Exchange (SSX), (APXL)"],
            ["name" => "Austria, Wiener Börse (VIE), (XWBO)"],
            ["name" => "Azerbaijan, Baku Stock Exchange, (BSEX)"],
            ["name" => "Bahamas, Bahamas International Securities Exchange (BISX), (XBAA)"],
            ["name" => "Bahrain, Bahrain Bourse (BSE), (XBAH)"],
            ["name" => "Bangladesh, Chittagong Stock Exchange (CSE), (XCHG)"],
            ["name" => "Bangladesh, Dhaka Stock Exchange (DSE), (XDHA)"],
            ["name" => "Barbados, Barbados Stock Exchange (BSE), (XBAB)"],
            ["name" => "Belarus, Belarusian Currency and Stock Exchange (BCSE), (BCSE)"],
            ["name" => "Belgium, Euronext Brussels (EBR), (XBRU)"],
            ["name" => "Bermuda, Bermuda Stock Exchange (BSX), (XBDA)"],
            ["name" => "Bolivia, Bolsa de Valores de Bolivia, (XBOL)"],
            ["name" => "Bosnia and Herzegovina, Banja Luka Stock Exchange (BLSE), (XBLB)"],
            ["name" => "Bosnia and Herzegovina, Sarajevo Stock Exchange (SASE), (XSSE)"],
            ["name" => "Botswana, Botswana Stock Exchange (BOT), (XBOT)"],
            ["name" => "Brazil, B3 - Brasil Bolsa Balcão (BVMF), (BVMF)"],
            ["name" => "Brazil, Bolsa de Valores Minab - Espírito Santo, (BOVM)"],
            ["name" => "Bulgaria, Bulgarian Stock Exchange (BSE), (XBUL)"],
            ["name" => "Cambodia, Cambodia Securities Exchange (CSX), (XCSX)"],
            ["name" => "Canada, Neo Exchange - Neo-L (NEO-L), (NEOE)"],
            ["name" => "Canada, Canadian Securities Exchange (CNSX), (XCNQ)"],
            ["name" => "Canada, Montreal Exchange (CDE), (XMOD)"],
            ["name" => "Canada, Nasdaq Canada, (XCSD)"],
            ["name" => "Canada, Toronto Stock Exchange (TSE), (XTSE)"],
            ["name" => "Cayman Islands, Cayman Islands Stock Exchange, (XCAY)"],
            ["name" => "Chile, Santiago Stock Exchange, (XSGO)"],
            ["name" => "Chile, Valparaiso Stock Exchange, (BOVA)"],
            ["name" => "China, Shanghai Stock Exchange (SHA), (XSHG)"],
            ["name" => "China, Shenzhen Stock Exchange (SHE), (XSHE)"],
            ["name" => "Colombia, Bolsa de Valores de Colombia (BVC), (XBOG)"],
            ["name" => "Costa Rica, Bolsa Nacional de Valores de Costa Rica (BNV), (XBNV)"],
            ["name" => "Croatia, Zagreb Stock Exchange, (XZAG)"],
            ["name" => "Curacao, Dutch Caribbean Securities Exchange (DCSX), (DCSX)"],
            ["name" => "Cyprus, Cyprus Stock Exchange (CSE), (XCYS)"],
            ["name" => "Czech Republic, Prague Stock Exchange (PSE), (XPRAG)"],
            ["name" => "Czech Republic, RM-System Czech Stock Exchange (RMS CZ), (XRMZ)"],
            ["name" => "Denmark, Nasdaq Copenhagen (CPH), (XCSE)"],
            ["name" => "Dominican Republic, Bolsa de Valores de la República Dominicana (BVRD), (XBVR)"],
            ["name" => "Ecuador, Bolsa de Valores de Guayaquil, (XGUA)"],
            ["name" => "Ecuador, Bolsa de Valores de Quito, (XQUI)"],
            ["name" => "Egypt, Egyptian Exchange (CAI), (XCAI)"],
            ["name" => "Egypt, Nilex, (NILX)"],
            ["name" => "El Salvador, Bolsa de Valores de El Salvador, (XSVA)"],
            ["name" => "Estonia, Tallinn Stock Exchange, (XTAL)"],
            ["name" => "Fiji, South Pacific Stock Exchange, (XSPS)"],
            ["name" => "Finland, Nasdaq Helsinki (HEL), (XHEL)"],
            ["name" => "France, Euronext Paris (EPA), (XPAR)"],
            ["name" => "Georgia, Georgian Stock Exchange, (XGSE)"],
            ["name" => "Germany, XETRA (ETR), (XETR)"],
            ["name" => "Germany, Börse Berlin (FRA), (XBER)"],
            ["name" => "Germany, Börse Düsseldorf, (XDUS)"],
            ["name" => "Germany, Börse München, (XMUN)"],
            ["name" => "Germany, Börse Stuttgart, (XSTU)"],
            ["name" => "Germany, Deutsche Börse Group (FRA), (XFRA)"],
            ["name" => "Germany, Eurex, (XEUR)"],
            ["name" => "Germany, Tradegate Exchange, (TGAT)"],
            ["name" => "Ghana, Ghana Stock Exchange, (XGHA)"],
            ["name" => "Gibraltar, Gibraltar Stock Exchange, (GSXL)"],
            ["name" => "Greece, Athens Stock Exchange, (ASEX)"],
            ["name" => "Guatemala, Bolsa Nacional de Valores, (XGTG)"],
            ["name" => "Guernsey, International Stock Exchange, (XCIE)"],
            ["name" => "Guyana, Guyana Stock Exchange, (GSCI)"],
            ["name" => "Honduras, Bolsa Centroamericana de Valores, (XBCV)"],
            ["name" => "Hong Kong, Hong Kong Growth Enterprise Market, (XGEM)"],
            ["name" => "Hong Kong, Hong Kong Stock Exchange (HKG), (XHKG)"],
            ["name" => "Hungary, Budapest Stock Exchange (BDP), (XBUD)"],
            ["name" => "Iceland, Nasdaq Iceland, (XICE)"],
            ["name" => "India, Bangalore Stock Exchange, (XBAN)"],
            ["name" => "India, Bombay Stock Exchange (BOM), (XBOM)"],
            ["name" => "India, BSE SME, (BSME)"],
            ["name" => "India, Calcutta Stock Exchange, (XCAL)"],
            ["name" => "India, Delhi Stock Exchange, (XDES)"],
            ["name" => "India, Inter-Connected Stock Exchange of India, (ISEX)"],
            ["name" => "India, National Stock Exchange of India (NSE), (XNSE)"],
            ["name" => "India, OTC Exchange of India, (OTCX)"],
            ["name" => "India, United Stock Exchange of India, (XUSE)"],
            ["name" => "Indonesia, Indonesia Stock Exchange (JAK), (XIDX)"],
            ["name" => "Iran, Tehran Stock Exchange, (XTEH)"],
            ["name" => "Iraq, Iraq Stock Exchange, (XIQS)"],
            ["name" => "Ireland, Irish Stock Exchange (IRE), (XDUB)"],
            ["name" => "Israel, Tel Aviv Stock Exchange (TLV), (XTAE)"],
            ["name" => "Italy, Borsa Italiana, (XMIL)"],
            ["name" => "Ivory Coast, Bourse Regionale des Valeurs Mobilieres, (XBRV)"],
            ["name" => "Jamaica, Jamaica Stock Exchange, (XJAM)"],
            ["name" => "Japan, Chi-X Japan, (CHIJ)"],
            ["name" => "Japan, Fukuoka Stock Exchange, (XFKA)"],
            ["name" => "Japan, Japan Exchange Group (JPX), (XJPX)"],
            ["name" => "Japan, Nagoya Stock Exchange (NSE), (XNGO)"],
            ["name" => "Japan, Sapporo Securities Exchange, (XSAP)"],
            ["name" => "Japan, SBI Japannext, (SBIJ)"],
            ["name" => "Jordan, Amman Stock Exchange, (XAMM)"],
            ["name" => "Kazakhstan, Astana International Financial Centre, (AIXK)"],
            ["name" => "Kazakhstan, Kazakhstan Stock Exchange, (XKAZ)"],
            ["name" => "Kenya, Nairobi Stock Exchange, (XNAI)"],
            ["name" => "Kuwait, Kuwait Stock Exchange, (XKUW)"],
            ["name" => "Kyrgyzstan, Kyrgyz Stock Exchange, (XKSE)"],
            ["name" => "Laos, Lao Securities Exchange, (XLAO)"],
            ["name" => "Latvia, Riga Stock Exchange, (XRIS)"],
            ["name" => "Lebanon, Beirut Stock Exchange, (XBEY)"],
            ["name" => "Lithuania, Vilnius Stock Exchange, (XLIT)"],
            ["name" => "Luxembourg, Luxembourg Stock Exchange, (XLUX)"],
            ["name" => "Macedonia, Macedonian Stock Exchange, (XMAE)"],
            ["name" => "Malawi, Malawi Stock Exchange, (XMSW)"],
            ["name" => "Malaysia, Bursa Malaysia (KUL), (XKLS)"],
            ["name" => "Maldives, Maldives Stock Exchange, (MALX)"],
            ["name" => "Malta, Malta Stock Exchange, (XMAL)"],
            ["name" => "Malta, Malta Stock Exchange Prospects, (PROS)"],
            ["name" => "Mauritius, Stock Exchange of Mauritius, (XMAU)"],
            ["name" => "Mexico, BIVA, (BIVA)"],
            ["name" => "Mexico, Bolsa Mexicana de Valores (BMV), (XMEX)"],
            ["name" => "Moldova, Moldova Stock Exchange, (XMOL)"],
            ["name" => "Mongolia, Mongolian Stock Exchange, (XULA)"],
            ["name" => "Montenegro, Montenegro Stock Exchange, (XMNX)"],
            ["name" => "Morocco, Casablanca Stock Exchange, (XCAS)"],
            ["name" => "Mozambique, Bolsa de Valores de Mozambique, (XBVM)"],
            ["name" => "Namibia, Namibian Stock Exchange, (XNAM)"],
            ["name" => "Nepal, Nepal Stock Exchange, (XNEP)"],
            ["name" => "Netherlands, Euronext Amsterdam (AMS), (XAMS)"],
            ["name" => "Netherlands, Nxchange, (XNXC)"],
            ["name" => "New Zealand, New Zealand Exchange (NZE), (XNZE)"],
            ["name" => "Nicaragua, Bolsa de Valores de Nicaragua, (XMAN)"],
            ["name" => "Nigeria, Nigerian Stock Exchange, (XNSA)"],
            ["name" => "Norway, Oslo Stock Exchange, (XOSL)"],
            ["name" => "Oman, Muscat Securities Market, (XMUS)"],
            ["name" => "Pakistan, Pakistan Stock Exchange (KAR), (XKAR)"],
            ["name" => "Palestine, Palestine Securities Exchange, (XPAE)"],
            ["name" => "Panama, Bolsa de Valores de Panama, (XPTY)"],
            ["name" => "Papua New Guinea, Port Moresby Stock Exchange, (XPOM)"],
            ["name" => "Paraguay, Bolsa de Valores & Productos de Asuncíon, (XVPA)"],
            ["name" => "Peru, Bolsa de Valores de Lima, (XLIM)"],
            ["name" => "Philippines, Philippine Stock Exchange (PSE), (XPHS)"],
            ["name" => "Poland, NewConnect, (XNCO)"],
            ["name" => "Poland, Warsaw Stock Exchange (WSE), (XWAR)"],
            ["name" => "Portugal, Euronext Lisbon (ELI), (XLIS)"],
            ["name" => "Portugal, OPEX, (OPEX)"],
            ["name" => "Qatar, Qatar Stock Exchange, (DSMD)"],
            ["name" => "Romania, Bucharest Stock Exchange, (XRAS)"],
            ["name" => "Russia, Moscow Exchange (MCX), (MISX)"],
            ["name" => "Russia, Saint Petersburg Stock Exchange, (XPET)"],
            ["name" => "Russia, Siberian Exchange, (XSIB)"],
            ["name" => "Rwanda, Rwanda Stock Exchange, (RSEX)"],
            ["name" => "Saint Kitts and Nevis, Eastern Caribbean Securities Exchange, (XECS)"],
            ["name" => "Saudi Arabia, Saudi Stock Exchange, (XSAU)"],
            ["name" => "Serbia, Belgrade Stock Exchange, (XBEL)"],
            ["name" => "Seychelles, Seychelles Securities Exchange (Trop-X), (TRPX)"],
            ["name" => "Singapore, Singapore Exchange (SGX), (XSES)"],
            ["name" => "Slovakia, Bratislava Stock Exchange, (XBRA)"],
            ["name" => "Slovenia, Ljubljana Stock Exchange, (XLJU)"],
            ["name" => "South Africa, ZAR X, (ZARX)"],
            ["name" => "South Africa, A2X Markets, (A2XX)"],
            ["name" => "South Africa, Johannesburg Stock Exchange (JNB), (XJSE)"],
            ["name" => "South Korea, Korea New Exchange, (XKON)"],
            ["name" => "South Korea, Korea Stock Exchange (KRX), (XKRX)"],
            ["name" => "South Korea, KOSDAQ Securities Exchange (KOSDAQ), (XKOS)"],
            ["name" => "Spain, Bolsa de Bilbao, (XBIL)"],
            ["name" => "Spain, Bolsa de Madrid (BME), (XMAD)"],
            ["name" => "Spain, Bolsa de Valencia, (XVAL)"],
            ["name" => "Spain, Borsa de Barcelona, (XBAR)"],
            ["name" => "Spain, Latibex, (XLAT)"],
            ["name" => "Sri Lanka, Colombo Stock Exchange, (XCOL)"],
            ["name" => "Sudan, Khartoum Stock Exchange, (XKHA)"],
            ["name" => "Swaziland, Swaziland Stock Exchange, (XSWA)"],
            ["name" => "Sweden, Aktietorget, (XSAT)"],
            ["name" => "Sweden, Nasdaq Stockholm (STO), (XSTO)"],
            ["name" => "Sweden, Nordic Growth Market, (XNGM)"],
            ["name" => "Switzerland, Berne eXchange, (XBRN)"],
            ["name" => "Switzerland, SIX Swiss Exchange (SWX), (XSWX)"],
            ["name" => "Syria, Damascus Securities Exchange, (XDSE)"],
            ["name" => "Taiwan, Taipei Exchange, (ROCO)"],
            ["name" => "Taiwan, Taiwan Stock Exchange (TPE), (XTAI)"],
            ["name" => "Tanzania, Dar-es-Salaam Stock Exchange, (XDAR)"],
            ["name" => "Thailand, Stock Exchange of Thailand (BAK), (XBKK)"],
            ["name" => "Trinidad and Tobago, Trinidad and Tobago Stock Exchange, (XTRN)"],
            ["name" => "Tunisia, Bourse de Tunis, (XTUN)"],
            ["name" => "Turkey, Borsa İstanbul (IST), (XIST)"],
            ["name" => "Uganda, Uganda Securities Exchange, (XUGA)"],
            ["name" => "Ukraine, East European Stock Exchange, (EESE)"],
            ["name" => "Ukraine, PFTS Ukraine Stock Exchange, (PFTS)"],
            ["name" => "Ukraine, Stock Exchange Perspectiva, (SEPE)"],
            ["name" => "Ukraine, Ukrainian Exchange, (UKEX)"],
            ["name" => "United Arab Emirates, Abu Dhabi Securities Market, (XADS)"],
            ["name" => "United Arab Emirates, Dubai Financial Market (DFM), (XDFM)"],
            ["name" => "United Arab Emirates, Nasdaq Dubai, (DIFX)"],
            ["name" => "United Kingdom, Euronext London, (XLDN)"],
            ["name" => "United Kingdom, Aquis Exchange (AQX), (AQXE)"],
            ["name" => "United Kingdom, Asset Match (AMPX), (AMPX)"],
            ["name" => "United Kingdom, London Stock Exchange (LON), (XLON)"],
            ["name" => "United Kingdom, Aquis Stock Exchange, (NEXX)"],
            ["name" => "United Kingdom, Turquoise, (TRQX)"],
            ["name" => "Uruguay, Bolsa de Valores de Montevideo (BVMT), (XMNT)"],
            ["name" => "Uruguay, Bolsa Electronica de Valores de Uruguay, (BVUR)"],
            ["name" => "Uzbekistan, Tashkent Stock Exchange (UZSE), (XSTE)"],
            ["name" => "Vietnam, Hanoi Stock Exchange (HNX), (HSTC)"],
            ["name" => "Vietnam, Ho Chi Minh Stock Exchange (HOSE), (XSTC)"],
            ["name" => "Zambia, Lusaka Stock Exchange, (XLUS)"],
            ["name" => "Zimbabwe, Zimbabwe Stock Exchange, (XZIM)"],
            ["name" => "Crypto - Centralized Exchange"],
            ["name" => "Crypto - Decentralized Exchange"],
            ["name" => "Forex exchange"]
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('exchange_tradeds');
    }
}
