<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateStatesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('states', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('country_id')->unsigned();
            $table->string('name', 64);
            $table->char('status', 1)->default(1);
            $table->foreign('country_id')->references('id')->on('countries')->onDelete('cascade')->onUpdate('cascade');
        });

        DB::table('states')->insert([
            ['name' => 'Alabama', 'country_id' => 1],
            ['name' => 'Alaska', 'country_id' => 1],
            ['name' => 'Arizona', 'country_id' => 1],
            ['name' => 'Arkansas', 'country_id' => 1],
            ['name' => 'California', 'country_id' => 1],
            ['name' => 'Colorado', 'country_id' => 1],
            ['name' => 'Connecticut', 'country_id' => 1],
            ['name' => 'Delaware', 'country_id' => 1],
            ['name' => 'Florida', 'country_id' => 1],
            ['name' => 'Georgia', 'country_id' => 1],
            ['name' => 'Hawaii', 'country_id' => 1],
            ['name' => 'Idaho', 'country_id' => 1],
            ['name' => 'Illinois', 'country_id' => 1],
            ['name' => 'Indiana', 'country_id' => 1],
            ['name' => 'Iowa', 'country_id' => 1],
            ['name' => 'Kansas', 'country_id' => 1],
            ['name' => 'Kentucky', 'country_id' => 1],
            ['name' => 'Louisiana', 'country_id' => 1],
            ['name' => 'Maine', 'country_id' => 1],
            ['name' => 'Maryland', 'country_id' => 1],
            ['name' => 'Massachusetts', 'country_id' => 1],
            ['name' => 'Michigan', 'country_id' => 1],
            ['name' => 'Minnesota', 'country_id' => 1],
            ['name' => 'Mississippi', 'country_id' => 1],
            ['name' => 'Missouri', 'country_id' => 1],
            ['name' => 'Montana', 'country_id' => 1],
            ['name' => 'Nebraska', 'country_id' => 1],
            ['name' => 'Nevada', 'country_id' => 1],
            ['name' => 'New Hampshire', 'country_id' => 1],
            ['name' => 'New Jersey', 'country_id' => 1],
            ['name' => 'New Mexico', 'country_id' => 1],
            ['name' => 'New York', 'country_id' => 1],
            ['name' => 'North Carolina', 'country_id' => 1],
            ['name' => 'North Dakota', 'country_id' => 1],
            ['name' => 'Ohio', 'country_id' => 1],
            ['name' => 'Oklahoma', 'country_id' => 1],
            ['name' => 'Oregon', 'country_id' => 1],
            ['name' => 'Pennsylvania', 'country_id' => 1],
            ['name' => 'Rhode Island', 'country_id' => 1],
            ['name' => 'South Carolina', 'country_id' => 1],
            ['name' => 'South Dakota', 'country_id' => 1],
            ['name' => 'Tennessee', 'country_id' => 1],
            ['name' => 'Texas', 'country_id' => 1],
            ['name' => 'Utah', 'country_id' => 1],
            ['name' => 'Vermont', 'country_id' => 1],
            ['name' => 'Virginia', 'country_id' => 1],
            ['name' => 'Washington', 'country_id' => 1],
            ['name' => 'West Virginia', 'country_id' => 1],
            ['name' => 'Wisconsin', 'country_id' => 1],
            ['name' => 'Wyoming', 'country_id' => 1],
            ['name' => 'New South Wales', 'country_id' => 14],
            ['name' => 'Queensland', 'country_id' => 14],
            ['name' => 'South Australia', 'country_id' => 14],
            ['name' => 'Tasmania', 'country_id' => 14],
            ['name' => 'Victoria', 'country_id' => 14],
            ['name' => 'Western Australia', 'country_id' => 14],
            ['name' => 'Acre', 'country_id' => 32],
            ['name' => 'Alagoas', 'country_id' => 32],
            ['name' => 'Amapá', 'country_id' => 32],
            ['name' => 'Amazonas', 'country_id' => 32],
            ['name' => 'Ceará', 'country_id' => 32],
            ['name' => 'Distrito Federal', 'country_id' => 32],
            ['name' => 'Espírito Santo', 'country_id' => 32],
            ['name' => 'Goiás', 'country_id' => 32],
            ['name' => 'Maranhão', 'country_id' => 32],
            ['name' => 'Mato Grosso', 'country_id' => 32],
            ['name' => 'Mato Grosso do Sul', 'country_id' => 32],
            ['name' => 'Minas Gerais', 'country_id' => 32],
            ['name' => 'Pará', 'country_id' => 32],
            ['name' => 'Paraíba', 'country_id' => 32],
            ['name' => 'Paraná', 'country_id' => 32],
            ['name' => 'Pernambuco', 'country_id' => 32],
            ['name' => 'Piauí', 'country_id' => 32],
            ['name' => 'Rio de Janeiro', 'country_id' => 32],
            ['name' => 'Rio Grande do Norte', 'country_id' => 32],
            ['name' => 'Rio Grande do Sul', 'country_id' => 32],
            ['name' => 'Rondônia', 'country_id' => 32],
            ['name' => 'Roraima', 'country_id' => 32],
            ['name' => 'Santa Catarina', 'country_id' => 32],
            ['name' => 'São Paulo', 'country_id' => 32],
            ['name' => 'Sergipe', 'country_id' => 32],
            ['name' => 'Tocantins', 'country_id' => 32],
            ['name' => 'Afar', 'country_id' => 71],
            ['name' => 'Amhara', 'country_id' => 71],
            ['name' => 'Benishangul-Gumuz', 'country_id' => 71],
            ['name' => 'Gambela', 'country_id' => 71],
            ['name' => 'Harari', 'country_id' => 71],
            ['name' => 'Oromia', 'country_id' => 71],
            ['name' => 'Sidama', 'country_id' => 71],
            ['name' => 'Somali', 'country_id' => 71],
            ['name' => 'South West', 'country_id' => 71],
            ['name' => 'Southern', 'country_id' => 71],
            ['name' => 'Tigray', 'country_id' => 71],
            ['name' => 'Baden-Württemberg', 'country_id' => 83],
            ['name' => 'Bavaria', 'country_id' => 83],
            ['name' => 'Berlin', 'country_id' => 83],
            ['name' => 'Brandenburg', 'country_id' => 83],
            ['name' => 'Bremen', 'country_id' => 83],
            ['name' => 'Hamburg', 'country_id' => 83],
            ['name' => 'Hesse', 'country_id' => 83],
            ['name' => 'Lower Saxony', 'country_id' => 83],
            ['name' => 'Mecklenburg-Western Pomerania', 'country_id' => 83],
            ['name' => 'North Rhine-Westphalia', 'country_id' => 83],
            ['name' => 'Rhineland-Palatinate', 'country_id' => 83],
            ['name' => 'Saarland', 'country_id' => 83],
            ['name' => 'Saxony', 'country_id' => 83],
            ['name' => 'Saxony-Anhalt', 'country_id' => 83],
            ['name' => 'Schleswig-Holstein', 'country_id' => 83],
            ['name' => 'Thuringia', 'country_id' => 83],
            ['name' => 'Andhra Pradesh', 'country_id' => 103],
            ['name' => 'Arunachal Pradesh', 'country_id' => 103],
            ['name' => 'Assam', 'country_id' => 103],
            ['name' => 'Bihar', 'country_id' => 103],
            ['name' => 'Chhattisgarh', 'country_id' => 103],
            ['name' => 'Goa', 'country_id' => 103],
            ['name' => 'Gujarat', 'country_id' => 103],
            ['name' => 'Haryana', 'country_id' => 103],
            ['name' => 'Himachal Pradesh', 'country_id' => 103],
            ['name' => 'Jharkhand', 'country_id' => 103],
            ['name' => 'Karnataka', 'country_id' => 103],
            ['name' => 'Kerala', 'country_id' => 103],
            ['name' => 'Madhya Pradesh', 'country_id' => 103],
            ['name' => 'Maharashtra', 'country_id' => 103],
            ['name' => 'Manipur', 'country_id' => 103],
            ['name' => 'Meghalaya', 'country_id' => 103],
            ['name' => 'Mizoram', 'country_id' => 103],
            ['name' => 'Nagaland', 'country_id' => 103],
            ['name' => 'Odisha', 'country_id' => 103],
            ['name' => 'Punjab', 'country_id' => 103],
            ['name' => 'Rajasthan', 'country_id' => 103],
            ['name' => 'Sikkim', 'country_id' => 103],
            ['name' => 'Tamil Nadu', 'country_id' => 103],
            ['name' => 'Telangana', 'country_id' => 103],
            ['name' => 'Tripura', 'country_id' => 103],
            ['name' => 'Uttar Pradesh', 'country_id' => 103],
            ['name' => 'Uttarakhand', 'country_id' => 103],
            ['name' => 'West Bengal', 'country_id' => 103],
            ['name' => 'Aguascalientes', 'country_id' => 144],
            ['name' => 'Baja California', 'country_id' => 144],
            ['name' => 'Baja California Sur', 'country_id' => 144],
            ['name' => 'Campeche', 'country_id' => 144],
            ['name' => 'Chiapas', 'country_id' => 144],
            ['name' => 'Chihuahua', 'country_id' => 144],
            ['name' => 'Coahuila', 'country_id' => 144],
            ['name' => 'Colima', 'country_id' => 144],
            ['name' => 'Durango', 'country_id' => 144],
            ['name' => 'Guanajuato', 'country_id' => 144],
            ['name' => 'Guerrero', 'country_id' => 144],
            ['name' => 'Hidalgo', 'country_id' => 144],
            ['name' => 'Jalisco', 'country_id' => 144],
            ['name' => 'México', 'country_id' => 144],
            ['name' => 'Michoacán', 'country_id' => 144],
            ['name' => 'Morelos', 'country_id' => 144],
            ['name' => 'Nayarit', 'country_id' => 144],
            ['name' => 'Nuevo León', 'country_id' => 144],
            ['name' => 'Oaxaca', 'country_id' => 144],
            ['name' => 'Puebla', 'country_id' => 144],
            ['name' => 'Querétaro', 'country_id' => 144],
            ['name' => 'Quintana Roo', 'country_id' => 144],
            ['name' => 'San Luis Potosí', 'country_id' => 144],
            ['name' => 'Sinaloa', 'country_id' => 144],
            ['name' => 'Sonora', 'country_id' => 144],
            ['name' => 'Tabasco', 'country_id' => 144],
            ['name' => 'Tamaulipas', 'country_id' => 144],
            ['name' => 'Tlaxcala', 'country_id' => 144],
            ['name' => 'Veracruz', 'country_id' => 144],
            ['name' => 'Yucatán', 'country_id' => 144],
            ['name' => 'Zacatecas', 'country_id' => 144],
            ['name' => 'Chuuk', 'country_id' => 145],
            ['name' => 'Kosrae', 'country_id' => 145],
            ['name' => 'Pohnpei', 'country_id' => 145],
            ['name' => 'Yap', 'country_id' => 145],
            ['name' => 'Abia', 'country_id' => 162],
            ['name' => 'Adamawa', 'country_id' => 162],
            ['name' => 'Akwa Ibom', 'country_id' => 162],
            ['name' => 'Anambra', 'country_id' => 162],
            ['name' => 'Bauchi', 'country_id' => 162],
            ['name' => 'Bayelsa', 'country_id' => 162],
            ['name' => 'Benue', 'country_id' => 162],
            ['name' => 'Borno', 'country_id' => 162],
            ['name' => 'Cross River', 'country_id' => 162],
            ['name' => 'Delta', 'country_id' => 162],
            ['name' => 'Ebonyi', 'country_id' => 162],
            ['name' => 'Edo', 'country_id' => 162],
            ['name' => 'Ekiti', 'country_id' => 162],
            ['name' => 'Enugu', 'country_id' => 162],
            ['name' => 'Gombe', 'country_id' => 162],
            ['name' => 'Imo', 'country_id' => 162],
            ['name' => 'Jigawa', 'country_id' => 162],
            ['name' => 'Kaduna', 'country_id' => 162],
            ['name' => 'Kano', 'country_id' => 162],
            ['name' => 'Katsina', 'country_id' => 162],
            ['name' => 'Kebbi', 'country_id' => 162],
            ['name' => 'Kogi', 'country_id' => 162],
            ['name' => 'Kwara', 'country_id' => 162],
            ['name' => 'Lagos', 'country_id' => 162],
            ['name' => 'Nasarawa', 'country_id' => 162],
            ['name' => 'Niger', 'country_id' => 162],
            ['name' => 'Ogun', 'country_id' => 162],
            ['name' => 'Ondo', 'country_id' => 162],
            ['name' => 'Osun', 'country_id' => 162],
            ['name' => 'Oyo', 'country_id' => 162],
            ['name' => 'Plateau', 'country_id' => 162],
            ['name' => 'Rivers', 'country_id' => 162],
            ['name' => 'Sokoto', 'country_id' => 162],
            ['name' => 'Taraba', 'country_id' => 162],
            ['name' => 'Yobe', 'country_id' => 162],
            ['name' => 'Zamfara', 'country_id' => 162],
            ['name' => 'Central Equatoria', 'country_id' => 208],
            ['name' => 'Eastern Equatoria', 'country_id' => 208],
            ['name' => 'Jonglei', 'country_id' => 208],
            ['name' => 'Lakes', 'country_id' => 208],
            ['name' => 'Northern Bahr el Ghazal', 'country_id' => 208],
            ['name' => 'Unity', 'country_id' => 208],
            ['name' => 'Upper Nile', 'country_id' => 208],
            ['name' => 'Warrap', 'country_id' => 208],
            ['name' => 'Western Bahr el Ghazal', 'country_id' => 208],
            ['name' => 'Western Equatoria', 'country_id' => 208],
            ['name' => 'Chin', 'country_id' => 153],
            ['name' => 'Kachin', 'country_id' => 153],
            ['name' => 'Kayah', 'country_id' => 153],
            ['name' => 'Kayin', 'country_id' => 153],
            ['name' => 'Mon', 'country_id' => 153],
            ['name' => 'Rakhine', 'country_id' => 153],
            ['name' => 'Shan', 'country_id' => 153],
            ['name' => 'Aimeliik', 'country_id' => 169],
            ['name' => 'Airai', 'country_id' => 169],
            ['name' => 'Angaur', 'country_id' => 169],
            ['name' => 'Hatohobei', 'country_id' => 169],
            ['name' => 'Kayangel', 'country_id' => 169],
            ['name' => 'Koror', 'country_id' => 169],
            ['name' => 'Melekeok', 'country_id' => 169],
            ['name' => 'Ngiwal', 'country_id' => 169],
            ['name' => 'Ngchesar', 'country_id' => 169],
            ['name' => 'Ngatpang', 'country_id' => 169],
            ['name' => 'Ngeremlengui', 'country_id' => 169],
            ['name' => 'Ngardmau', 'country_id' => 169],
            ['name' => 'Ngarchelong', 'country_id' => 169],
            ['name' => 'Ngaraard', 'country_id' => 169],
            ['name' => 'Peleliu', 'country_id' => 169],
            ['name' => 'Sonsorol', 'country_id' => 169],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('states');
    }
}
